### ISSUE TITLE
REST OAuth authorize for an admin fails

### ISSUE THREAD

**Issue by leesbian** [mageplus/mageplus#22]
Hi,
I can't register a admin user with a consumer.
I'm stuck at "Oauth Authorize" phase: http://magentohost/admin/oauth_authorize. 
I get this exception:

2012-05-16T07:04:49+00:00 DEBUG (7): Exception message: oauth_token
Trace: #0 D:dumneaniWorkinstallframeworkxampphtdocslimoappcodecoreMageOauthModelServer.php(451): Mage::exception('Mage_Oauth', 'oauth_token', 2)
#1 D:dumneaniWorkinstallframeworkxampphtdocslimoappcodecoreMageOauthModelServer.php(573): Mage_Oauth_Model_Server->_throwException('oauth_token', 2)
#2 D:dumneaniWorkinstallframeworkxampphtdocslimoappcodecoreMageOauthModelServer.php(336): Mage_Oauth_Model_Server->_validateTokenParam()
#3 D:dumneaniWorkinstallframeworkxampphtdocslimoappcodecoreMageOauthModelServer.php(656): Mage_Oauth_Model_Server->_initToken()
#4 D:dumneaniWorkinstallframeworkxampphtdocslimoappcodecoreMageOauthcontrollersAdminhtmlOauthAuthorizeController.php(117): Mage_Oauth_Model_Server->checkAuthorizeRequest()
#5 D:dumneaniWorkinstallframeworkxampphtdocslimoappcodecoreMageOauthcontrollersAdminhtmlOauthAuthorizeController.php(84): Mage_Oauth_Adminhtml_Oauth_AuthorizeController->_initForm()

I succesfully authorized/registered a token(on a consumer) for a CUSTOMER, and it's AuthorizeController.php use the same Server.php, so I suppose that issue may come from the difference of AuthorizationController used for CUSTOMER vs ADMIN user.

I'm not a PHP developer and I don't understand all details.
Thanks

Imported from : http://www.magentocommerce.com/bug-tracking/issue?issue=13640

**Comment by tux-rampage** [comment]
Do you mind if I take a look at this issue?

**Comment by LeeSaferite** [comment]
Feel free to look at, verify, and fix if you like.  Contributions are welcome.
