### ISSUE TITLE
Complex filter with operators broken in API V2

### ISSUE THREAD

**Issue by leesbian** [mageplus/mageplus#75]
It's impossible to use complex filters with operators in API V2 for salesOrderInvoiceList and salesOrderCreditmemoList.

Fault message:

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'gt' in 'where clause'

System.log:

2012-04-04T13:52:41+00:00 DEBUG (7): Undefined index: keyD:xampphtdocsmagentoappcodecoreMageSalesModelOrderInvoiceApiV2.php
2012-04-04T13:52:41+00:00 DEBUG (7): Undefined index: valueD:xampphtdocsmagentoappcodecoreMageSalesModelOrderInvoiceApiV2.php

Exception.log:

2012-04-04T13:52:41+00:00 ERR (3): 
exception 'PDOException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'gt' in 'where clause'' in D:xampphtdocsmagentolibZendDbStatementPdo.php:228
Stack trace:
#0 D:xampphtdocsmagentolibZendDbStatementPdo.php(228): PDOStatement->execute(Array)
#1 D:xampphtdocsmagentolibVarienDbStatementPdoMysql.php(110): Zend_Db_Statement_Pdo->_execute(Array)
#2 D:xampphtdocsmagentolibZendDbStatement.php(300): Varien_Db_Statement_Pdo_Mysql->_execute(Array)
#3 D:xampphtdocsmagentolibZendDbAdapterAbstract.php(479): Zend_Db_Statement->execute(Array)
#4 D:xampphtdocsmagentolibZendDbAdapterPdoAbstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT `main_ta...', Array)
#5 D:xampphtdocsmagentolibVarienDbAdapterPdoMysql.php(419): Zend_Db_Adapter_Pdo_Abstract->query('SELECT `main_ta...', Array)
#6 D:xampphtdocsmagentolibZendDbAdapterAbstract.php(734): Varien_Db_Adapter_Pdo_Mysql->query('SELECT `main_ta...', Array)
#7 D:xampphtdocsmagentolibVarienDataCollectionDb.php(734): Zend_Db_Adapter_Abstract->fetchAll('SELECT `main_ta...', Array)
#8 D:xampphtdocsmagentoappcodecoreMageCoreModelResourceDbCollectionAbstract.php(521): Varien_Data_Collection_Db->_fetchAll('SELECT `main_ta...', Array)
#9 D:xampphtdocsmagentolibVarienDataCollectionDb.php(566): Mage_Core_Model_Resource_Db_Collection_Abstract->getData()
#10 D:xampphtdocsmagentolibVarienDataCollection.php(741): Varien_Data_Collection_Db->load()
#11 D:xampphtdocsmagentoappcodecoreMageSalesModelOrderInvoiceApiV2.php(98): Varien_Data_Collection->getIterator()
#12 [internal function]: Mage_Sales_Model_Order_Invoice_Api_V2->items(Object(stdClass))
#13 D:xampphtdocsmagentoappcodecoreMageApiModelServerHandlerAbstract.php(296): call_user_func_array(Array, Array)
#14 D:xampphtdocsmagentoappcodecoreMageApiModelServerWsiHandler.php(78): Mage_Api_Model_Server_Handler_Abstract->call('a4b881c7082b717...', 'order_invoice.l...', Array)
#15 [internal function]: Mage_Api_Model_Server_WSI_Handler->__call('salesOrderInvoi...', Array)
#16 [internal function]: Mage_Api_Model_Server_WSI_Handler->salesOrderInvoiceList(Object(stdClass))
#17 D:xampphtdocsmagentolibZendSoapServer.php(832): SoapServer->handle('<s:Envelope xml...')
#18 D:xampphtdocsmagentoappcodecoreMageApiModelServerWsiAdapterSoap.php(89): Zend_Soap_Server->handle()
#19 D:xampphtdocsmagentoappcodecoreMageApiModelServer.php(138): Mage_Api_Model_Server_WSI_Adapter_Soap->run()
#20 D:xampphtdocsmagentoappcodecoreMageApicontrollersV2SoapController.php(46): Mage_Api_Model_Server->run()
#21 D:xampphtdocsmagentoappcodecoreMageCoreControllerVarienAction.php(419): Mage_Api_V2_SoapController->indexAction()
#22 D:xampphtdocsmagentoappcodecoreMageCoreControllerVarienRouterStandard.php(250): Mage_Core_Controller_Varien_Action->dispatch('index')
#23 D:xampphtdocsmagentoappcodecoreMageCoreControllerVarienFront.php(176): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#24 D:xampphtdocsmagentoappcodecoreMageCoreModelApp.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#25 D:xampphtdocsmagentoappMage.php(683): Mage_Core_Model_App->run(Array)
#26 D:xampphtdocsmagentoindex.php(87): Mage::run('', 'store')
#27 {main}

Next exception 'Zend_Db_Statement_Exception' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'gt' in 'where clause'' in D:xampphtdocsmagentolibZendDbStatementPdo.php:234
Stack trace:
#0 D:xampphtdocsmagentolibVarienDbStatementPdoMysql.php(110): Zend_Db_Statement_Pdo->_execute(Array)
#1 D:xampphtdocsmagentolibZendDbStatement.php(300): Varien_Db_Statement_Pdo_Mysql->_execute(Array)
#2 D:xampphtdocsmagentolibZendDbAdapterAbstract.php(479): Zend_Db_Statement->execute(Array)
#3 D:xampphtdocsmagentolibZendDbAdapterPdoAbstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT `main_ta...', Array)
#4 D:xampphtdocsmagentolibVarienDbAdapterPdoMysql.php(419): Zend_Db_Adapter_Pdo_Abstract->query('SELECT `main_ta...', Array)
#5 D:xampphtdocsmagentolibZendDbAdapterAbstract.php(734): Varien_Db_Adapter_Pdo_Mysql->query('SELECT `main_ta...', Array)
#6 D:xampphtdocsmagentolibVarienDataCollectionDb.php(734): Zend_Db_Adapter_Abstract->fetchAll('SELECT `main_ta...', Array)
#7 D:xampphtdocsmagentoappcodecoreMageCoreModelResourceDbCollectionAbstract.php(521): Varien_Data_Collection_Db->_fetchAll('SELECT `main_ta...', Array)
#8 D:xampphtdocsmagentolibVarienDataCollectionDb.php(566): Mage_Core_Model_Resource_Db_Collection_Abstract->getData()
#9 D:xampphtdocsmagentolibVarienDataCollection.php(741): Varien_Data_Collection_Db->load()
#10 D:xampphtdocsmagentoappcodecoreMageSalesModelOrderInvoiceApiV2.php(98): Varien_Data_Collection->getIterator()
#11 [internal function]: Mage_Sales_Model_Order_Invoice_Api_V2->items(Object(stdClass))
#12 D:xampphtdocsmagentoappcodecoreMageApiModelServerHandlerAbstract.php(296): call_user_func_array(Array, Array)
#13 D:xampphtdocsmagentoappcodecoreMageApiModelServerWsiHandler.php(78): Mage_Api_Model_Server_Handler_Abstract->call('a4b881c7082b717...', 'order_invoice.l...', Array)
#14 [internal function]: Mage_Api_Model_Server_WSI_Handler->__call('salesOrderInvoi...', Array)
#15 [internal function]: Mage_Api_Model_Server_WSI_Handler->salesOrderInvoiceList(Object(stdClass))
#16 D:xampphtdocsmagentolibZendSoapServer.php(832): SoapServer->handle('<s:Envelope xml...')
#17 D:xampphtdocsmagentoappcodecoreMageApiModelServerWsiAdapterSoap.php(89): Zend_Soap_Server->handle()
#18 D:xampphtdocsmagentoappcodecoreMageApiModelServer.php(138): Mage_Api_Model_Server_WSI_Adapter_Soap->run()
#19 D:xampphtdocsmagentoappcodecoreMageApicontrollersV2SoapController.php(46): Mage_Api_Model_Server->run()
#20 D:xampphtdocsmagentoappcodecoreMageCoreControllerVarienAction.php(419): Mage_Api_V2_SoapController->indexAction()
#21 D:xampphtdocsmagentoappcodecoreMageCoreControllerVarienRouterStandard.php(250): Mage_Core_Controller_Varien_Action->dispatch('index')
#22 D:xampphtdocsmagentoappcodecoreMageCoreControllerVarienFront.php(176): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#23 D:xampphtdocsmagentoappcodecoreMageCoreModelApp.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#24 D:xampphtdocsmagentoappMage.php(683): Mage_Core_Model_App->run(Array)
#25 D:xampphtdocsmagentoindex.php(87): Mage::run('', 'store')
#26 {main}

Reproduce C# code (WS-I compliant):

filters f = new filters();
f.complex_filter = new complexFilter[] { 
new complexFilter() { 
key = "created_at",
value = new associativeMultiEntity() {
key = "gt",
value = new string[] { DateTime.Today.AddDays(-30).ToString("yy-MM-dd HH:mm:ss") } 
}
}

};

var invoices = proxy.salesOrderInvoiceList(sessionId, f); //FAULTING
// var orders = proxy.salesOrderList(sessionId, f); //WORKS!!

imported from : http://www.magentocommerce.com/bug-tracking/issue?issue=13362

**Comment by stereoscope** [comment]
http://stackoverflow.com/questions/11374525/magento-1-7-soap-request-using-filter-and-or-complex-filter

**Comment by vendamere** [comment]
I'm experiencing this issue too. With WS-I compliance turned on I can't get the filters to work. Not with salesOrderList either. I get the same SQL error message.

I found this same issue here http://www.magentocommerce.com/boards/viewthread/260777/#t389539 back from 2009 in version 1.6 which is what I'm also using. Seems like the thread linked above had a good start on tracking down the issue, the SOAP message isn't being unpacked properly. I'm not familiar with Magento enough to start tracking it down, but hopefully it will point someone in the right direction.

**Comment by shivali-at-earth** [comment]
I am facing same issue fro WSI Compliance Mode On for Magento.
